### Get all rooms
GET http://localhost:8080/api/rooms

###

### Create room
POST http://localhost:8080/api/rooms
Content-Type: application/json

{
  "name": "Cabinet 101",
  "description": "Etajul 1"
}

> {%
    client.global.set("roomId", response.body.id);
%}

###

### Get room by ID
GET http://localhost:8080/api/rooms/{{roomId}}

###

### Update room
PUT http://localhost:8080/api/rooms/{{roomId}}
Content-Type: application/json

{
  "name": "Cabinet 102",
  "description": "Etajul 2"
}

###

### Delete room
DELETE http://localhost:8080/api/rooms/{{roomId}}
