spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/medsched_dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Creează/actualizează tabelele automat în dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect